### ISSUE TITLE
Can't run the bot

### ISSUE THREAD

**Issue by pagelift-be** [kdrag0n/pyrobud#1]
I get following error when trying to start the bot:

root@ubuntu:~/pyrobud# python3 main.py
  File "main.py", line 8
    config: bot.Config = toml.load('config.toml')
          ^
SyntaxError: invalid syntax

**Comment by kdrag0n** [comment]
> I get following error when trying to start the bot:
> 
> root@ubuntu:~/pyrobud# python3 main.py
> File "main.py", line 8
> config: bot.Config = toml.load('config.toml')
> ^
> SyntaxError: invalid syntax

You need Python 3.7 or newer due to the use of type annotations.
