### ISSUE TITLE
Can't install new dependency: plyvel

### ISSUE THREAD

**Issue by Bluscream** [kdrag0n/pyrobud#6]
![image](https://user-images.githubusercontent.com/3318223/68742901-271dba80-05e9-11ea-82d2-53947ec43733.png)

**Comment by Bluscream** [comment]
I was able to fix it with `sudo apt install libleveldb1d libleveldb-dev python3-leveldb` but you should update the readme with it and maybe even add a notice somewhere :thinking: 

I'll keep this issue open until that's resolved.

**Comment by kdrag0n** [comment]
Resolved with the new README section on installation: https://github.com/kdrag0n/pyrobud#installation
