### ISSUE TITLE
[Feature Request] Module repository

### ISSUE THREAD

**Issue by Bluscream** [kdrag0n/pyrobud#8]
A nice thing to have would be a module that allows managing (installing/updating/removing) other modules. The concept is as follows:

- A module that allows interacting with repos ([Example](https://github.com/appu1232/Discord-Selfbot/blob/master/cogs/cog_download.py))
- A repo system based on JSON files ([Example 1](https://github.com/GriffinG1/Selfbot-Cogs/blob/master/cogs/linksplit.json), [Example 2](https://github.com/pathmann/pyTSon_repository/blob/master/repository.json))
- A official repository maintained by you where plugins can be submitted as pull requests to the main repository.json [Example](https://github.com/pathmann/pyTSon_repository) (Ideally supporting pip deps like the example)

Usage Mockup:

1. `.mod repo list` refreshes all repos and shows them as a list.
2. `.mod repo install ExampleModule` downloads the module from the repo to `pyrobud/custom_modules/ExampleModuly.py`, installs pip dependencies and loads the module
3. `mod delete ExampleModule` unloads ExampleModule and deletes `pyrobud/custom_modules/ExampleModuly.py`

**Comment by kdrag0n** [comment]
The `custom_modules` idea has been addressed with commit 164596db86b26f9a09283203dc2ba716026779a6.

There are no plans to create a full-fledged repository setup at this time, however this may be reconsidered if there is increased demand in the future.

**Comment by Bluscream** [comment]
@kdrag0n Looks like custom module commands are missing from the help now btw!
